simonsfoundation/spectrum-autism-prevalence-map

- spectrum/autism_prevalence_map/management/commands/pull_studies_from_gsheets.py
- spectrum/autism_prevalence_map/static/autism_prevalence_map/js/joint.js
- spectrum/autism_prevalence_map/static/autism_prevalence_map/js/list.js
- spectrum/autism_prevalence_map/static/autism_prevalence_map/js/map.js
- spectrum/autism_prevalence_map/templates/autism_prevalence_map/action_buttons.html
- spectrum/autism_prevalence_map/templates/autism_prevalence_map/list.html
- spectrum/autism_prevalence_map/templates/autism_prevalence_map/map.html
- spectrum/autism_prevalence_map/views.py
Added capacity to display income and education data, as well as to filter by those two data points, to both the map and the list views
> SPEC-288: Adding income and education filters

- spectrum/autism_prevalence_map/views.py
- spectrum/spectrum/settings.py
Changing response['status'] to 200 instead of OK in views.py, defining ALLOWED_HOSTS the same regardless of the value of DEBUG
modified:   spectrum/autism_prevalence_map/views.py
modified:   spectrum/spectrum/settings.py
> SPEC-301: Downloads not working

- spectrum/autism_prevalence_map/templates/autism_prevalence_map/about.html
modified:   spectrum/autism_prevalence_map/templates/autism_prevalence_map/about.html
> SPEC-324: Adding "cite the map" subnav item for this page

- spectrum/autism_prevalence_map/management/commands/pull_studies_from_gsheets.py
This PR adds more country codes.
> add more country codes

- spectrum/autism_prevalence_map/management/commands/pull_studies_from_gsheets.py
modified:   autism_prevalence_map/management/commands/pull_studies_from_gsheets.py
> Changing the sheets key

- spectrum/autism_prevalence_map/templates/autism_prevalence_map/base.html
Addressing QA request from Joel regarding search input text color.
> TTWWW-467: updated search input text color to med-navy

- spectrum/autism_prevalence_map/static/autism_prevalence_map/tailwind.config.js
- spectrum/autism_prevalence_map/static/autism_prevalence_map/ts/main.ts
- spectrum/autism_prevalence_map/static/autism_prevalence_map/ts/mobile-popup.ts
- spectrum/autism_prevalence_map/templates/autism_prevalence_map/base.html
- spectrum/autism_prevalence_map/templates/autism_prevalence_map/mobile_popup.html
Task: https://simonsfoundation.atlassian.net/browse/TTWWW-478
Figma designs: https://www.figma.com/design/wcJ1rzoLOkRaVuKp2Zae6F/Prevalence-Map?node-id=1013-11698&t=7p4vQCokTNj12i8b-0
> TTWWW-478: Prevalence Map mobile popup

- spectrum/autism_prevalence_map/templates/autism_prevalence_map/about.html
Task: https://simonsfoundation.atlassian.net/browse/TTWWW-480
Figma designs: https://www.figma.com/design/wcJ1rzoLOkRaVuKp2Zae6F/Prevalence-Map?node-id=957-14013&m=dev
> TTWWW-480: Capitalize all headers

- spectrum/autism_prevalence_map/templates/autism_prevalence_map/about.html
- spectrum/autism_prevalence_map/templates/autism_prevalence_map/base.html
- spectrum/autism_prevalence_map/templates/autism_prevalence_map/map.html
Task: https://simonsfoundation.atlassian.net/browse/TTWWW-480
Figma designs: https://www.figma.com/design/wcJ1rzoLOkRaVuKp2Zae6F/Prevalence-Map?node-id=957-14013&m=dev
> TTWWW-480: Fixes according to ticket comments

- spectrum/autism_prevalence_map/templates/autism_prevalence_map/mobile_popup.html
Task: https://simonsfoundation.atlassian.net/browse/TTWWW-478
Figma designs: https://www.figma.com/design/wcJ1rzoLOkRaVuKp2Zae6F/Prevalence-Map?node-id=1013-11698&t=7p4vQCokTNj12i8b-0
> TTWWW-478: Fix according to ticket comments

- spectrum/autism_prevalence_map/templates/autism_prevalence_map/base.html
- spectrum/autism_prevalence_map/templates/autism_prevalence_map/map.html
@yjfnyc update to re-add the padding classes to <main>. This keeps getting removed on merges.
> TTWWW-472: Update to padding on <main>

- spectrum/autism_prevalence_map/static/autism_prevalence_map/ts/map.ts
- spectrum/autism_prevalence_map/templates/autism_prevalence_map/map.html
Updated the welcome card copy based on Sam's comment in Jira:
https://simonsfoundation.atlassian.net/browse/TTWWW-472?focusedCommentId=109969
> TTWWW-472: Updated welcome card copy

- spectrum/autism_prevalence_map/templates/autism_prevalence_map/about.html
Task: https://simonsfoundation.atlassian.net/browse/TTWWW-480
Figma designs: https://www.figma.com/design/wcJ1rzoLOkRaVuKp2Zae6F/Prevalence-Map?node-id=957-14013&m=dev
> TTWWW-480: Fix according to ticket comments

- spectrum/autism_prevalence_map/static/autism_prevalence_map/tailwind/tailwind.css
- spectrum/autism_prevalence_map/static/autism_prevalence_map/ts/map.ts
- spectrum/autism_prevalence_map/templates/autism_prevalence_map/map.html
A couple small updates. You are right the extra .row was not needed anymore. And I missed updating one rounded border after merging.
> TTWWW-475: updates to remove unneeded div and corrected a rounded border

- spectrum/autism_prevalence_map/static/autism_prevalence_map/ts/map.ts
- spectrum/autism_prevalence_map/templates/autism_prevalence_map/map.html
Addressing Sam's comment here: https://simonsfoundation.atlassian.net/browse/TTWWW-475?focusedCommentId=110318
The tooltip copy has been updated on the timeline.
> TTWWW-475: Updated tooltip copy based on Sam's request

- spectrum/autism_prevalence_map/static/autism_prevalence_map/ts/list.ts
Tested now with various levels of filtering on Chrome, Safari, and Firefox.
> TTWWW-476: updates to allow collapse functionality to work after filtering

- spectrum/autism_prevalence_map/templates/autism_prevalence_map/about.html
- spectrum/autism_prevalence_map/templates/autism_prevalence_map/base.html
- spectrum/autism_prevalence_map/templates/autism_prevalence_map/list.html
- spectrum/autism_prevalence_map/templates/autism_prevalence_map/map.html
For Jira ticket [here](https://simonsfoundation.atlassian.net/browse/TTWWW-594).
> TTWWW-594: Updated SEO tags for prevalence map

- spectrum/autism_prevalence_map/templates/autism_prevalence_map/base.html
- spectrum/autism_prevalence_map/views.py
> TTWWW-593: Add "last updated" date to prev map code

- spectrum/autism_prevalence_map/static/autism_prevalence_map/ts/map.ts
Addressing comments from Joel [here](https://simonsfoundation.atlassian.net/browse/TTWWW-473?focusedCommentId=113916) in Jira.
First I adjusted how mega dot clustering works. Adding a way for clusters to merge to eliminate some of the use cases where outside dots look like they should be part of the cluster. Ultimately when clusters were calculated, it was from a first dot, then all dots within a radius of it. Where ideally clustering would happen around a center dot. This merging method was a good way to address this.
I also added a better way of calculating the size of unexpanded mega dots to better represent the number of dots inside.
Specifically addressing the Jira comments, mega dots will no longer re-form when zooming. Also now when clicking to expand a mega dot, it will zoom in …
> TTWWW-473: Mega Dot updates

- spectrum/autism_prevalence_map/templates/autism_prevalence_map/base.html
> Deploy Epic Branch TTWWW-468 to Develop
