spectrum/autism_prevalence_map/management/commands/pull_studies_from_gsheets.py
This PR is to plot Greece, Scotland, Taiwan, and South Korea correctly.
=> add region codes for greece, scotland, taiwan, and south korea

spectrum/autism_prevalence_map/templates/autism_prevalence_map/about.html, spectrum/autism_prevalence_map/views.py
jira ticket: [SPECWWW-724](https://simonsfoundation.atlassian.net/browse/SPECWWW-724)
=> Jinfeng/specwww 724: Fix overlapping text and remove newsletter sub field for Global Autism Prevalence Map

spectrum/autism_prevalence_map/admin.py, spectrum/autism_prevalence_map/templates/autism_prevalence_map/admin/bulk_import.html, spectrum/autism_prevalence_map/templates/autism_prevalence_map/admin/change_list.html, spectrum/autism_prevalence_map/views.py, spectrum/spectrum/settings.py
Jira ticket: [SPECWWW-770](https://simonsfoundation.atlassian.net/browse/SPECWWW-770), [SPECWWW-767](https://simonsfoundation.atlassian.net/browse/SPECWWW-767)
To test:
=> specwww 767/770: Add bulk import functionality to prevalence map backend panel/Improved download functionality for prevalence map

spectrum/autism_prevalence_map/admin.py
Jira ticket: [SPECWWW-818](https://simonsfoundation.atlassian.net/browse/SPECWWW-818)
To test:
=> specwww 818: Geo Info not Retrievable for Some Country Area Combinations

README.md, spectrum/autism_prevalence_map/static/autism_prevalence_map/js/list.js, spectrum/autism_prevalence_map/static/autism_prevalence_map/js/map.js, spectrum/autism_prevalence_map/templates/autism_prevalence_map/action_buttons.html, spectrum/autism_prevalence_map/templates/autism_prevalence_map/map.html
Jira ticket: [SPECWWW-866](https://simonsfoundation.atlassian.net/browse/SPECWWW-866)
To test:
=> specwww 866： Hide "income" and "education" columns from front-end of Prev Map

spectrum/autism_prevalence_map/templates/autism_prevalence_map/about.html, spectrum/autism_prevalence_map/templates/autism_prevalence_map/base.html, spectrum/autism_prevalence_map/views.py
https://simonsfoundation.atlassian.net/browse/TTWWW-354
=> TTWWW-354: change the meta info from spectrum to the transmitter

spectrum/autism_prevalence_map/static/autism_prevalence_map/ts/joint.ts
The code previously was looking for the class 'active' on the main navigation links. This changed where now the class text--red is in place when a link is active. This difference is breaking the map when filters are used.
=> TTWWW-477: Small update to allow map to work with active links

spectrum/autism_prevalence_map/static/autism_prevalence_map/ts/map.ts
Based on design's comment: https://simonsfoundation.atlassian.net/browse/TTWWW-475?focusedCommentId=110223
I have made the selected dot color on the timeline: #FEF9EE
=> TTWWW-475: Updated pinned dot color for timeline map pins

spectrum/autism_prevalence_map/templates/autism_prevalence_map/base.html
Task: https://simonsfoundation.atlassian.net/browse/TTWWW-568
=> TTWWW-568: Sticky nav for prevalence map

spectrum/autism_prevalence_map/static/autism_prevalence_map/tailwind.config.js, spectrum/autism_prevalence_map/static/autism_prevalence_map/ts/map.ts, spectrum/autism_prevalence_map/templates/autism_prevalence_map/map.html
Referencing this Jira ticket: https://simonsfoundation.atlassian.net/browse/TTWWW-571
I updated to account for all 4 links that were originally in the code.
=> TTWWW-571: Show multiple links on study card

spectrum/autism_prevalence_map/static/autism_prevalence_map/tailwind.config.js, spectrum/autism_prevalence_map/static/autism_prevalence_map/ts/joint.ts, spectrum/autism_prevalence_map/static/autism_prevalence_map/ts/list.ts, spectrum/autism_prevalence_map/static/autism_prevalence_map/ts/map.ts, spectrum/autism_prevalence_map/templates/autism_prevalence_map/action_buttons.html
This PR is for this Jira ticket: https://simonsfoundation.atlassian.net/browse/TTWWW-573
=> TTWWW-573: add box to show calculated mean on page

spectrum/autism_prevalence_map/templates/autism_prevalence_map/list.html
Task: https://simonsfoundation.atlassian.net/browse/TTWWW-580
Figma designs: https://www.figma.com/design/wcJ1rzoLOkRaVuKp2Zae6F/Prevalence-Map?node-id=2118-3703&m=dev
=> TTWWW-580: Sticky header on List view

spectrum/autism_prevalence_map/static/autism_prevalence_map/ts/map.ts
Addressing Sam's comment [here](https://simonsfoundation.atlassian.net/browse/TTWWW-475?focusedCommentId=111721).
=> TTWWW-475: updated timeline handles so that there can no longer be a min year greater than a max year

spectrum/autism_prevalence_map/static/autism_prevalence_map/ts/joint.ts, spectrum/autism_prevalence_map/static/autism_prevalence_map/ts/map.ts
Addressing Sam's comment [here](https://simonsfoundation.atlassian.net/browse/TTWWW-469?focusedCommentId=111722)
I went the route of disabling options that we don't want selectable (min year greater than the max year, max year less than min year). This was a more straight forward approach compared to removing and re-adding the options as needed, and felt like a better user experience to me so that you always know what years are available. I left a comment to Sam on the task letting him know I went this direction, so he can let us know if he wants them to be removed.
=> TTWWW-469: Updated min and max filters to not allow min years to be selected that are more than max year

spectrum/autism_prevalence_map/static/autism_prevalence_map/ts/joint.ts, spectrum/autism_prevalence_map/static/autism_prevalence_map/ts/main.ts, spectrum/autism_prevalence_map/templates/autism_prevalence_map/about.html, spectrum/autism_prevalence_map/templates/autism_prevalence_map/base.html, spectrum/autism_prevalence_map/views.py
This is addressing Sam's comment [here](https://simonsfoundation.atlassian.net/browse/TTWWW-573?focusedCommentId=111634). The comment was focused on the static mean box, but the real issue was that the filters would not persist when navigating to the about page and then back to the map or list page. So I made the joint.ts file be included on the about page, and then modified views.py and the about page to make sure that filter data was available on the about page.
=> TTWWW-573: Updates to allow map filters to stay active when navigating to the about page and back

spectrum/autism_prevalence_map/static/autism_prevalence_map/ts/map.ts
Addressing Sam's comment [here](https://simonsfoundation.atlassian.net/browse/TTWWW-471?focusedCommentId=112218).
Selected dots on the map and the timeline now move to the front.
=> TTWWW-471: Make sure selected map dots move to the front

spectrum/autism_prevalence_map/static/autism_prevalence_map/ts/joint.ts, spectrum/autism_prevalence_map/static/autism_prevalence_map/ts/map.ts
Addressing your comment here: "But I think it is a hack to tackle the symptom instead of the root cause.
I dug into the code a bit, and seemed to me the issue has to do with the timezone difference when a date string like '2010-01-01' and when this is in New York Eastern Time zone, it will get the date for Dec. 31, 2009.
The timeMin get date from yearsstudied_number_min, which as the above mentioned format, and timeMax get date from yearpublished and it only has format like '2010'. When you have time, can you please see if you can fix the root cause."
You were correct this was not the best way to handle it. I have now updated this in a better way by normalizing timeMin and timeMax to UTC. This also allowed me to remove the addition of an extra year to the timeline like I was doing before. …
=> TTWWW-475: updated to use UTC time and make more consistent

spectrum/autism_prevalence_map/views.py
Jira ticket: [TTWWW-581](https://simonsfoundation.atlassian.net/browse/TTWWW-581)
To test:
[TTWWW-581]: https://simonsfoundation.atlassian.net/browse/TTWWW-581?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ttwww-581: change name of prevalence map data file download

spectrum/autism_prevalence_map/admin.py, spectrum/autism_prevalence_map/templates/autism_prevalence_map/base.html, spectrum/autism_prevalence_map/views.py
This is an update based on Sam's comment [here](https://simonsfoundation.atlassian.net/browse/TTWWW-593?focusedCommentId=112957).
This value gets generated when something in the database gets updated. So locally I just opened a study and saved it, which generates the initial value.
=> TTWWW-593: Add "last updated" date to prev map code

spectrum/autism_prevalence_map/views.py, spectrum/spectrum/settings.py
Regarding [this](https://simonsfoundation.atlassian.net/browse/TTWWW-595) Jira ticket.
There are a few routes that we could go with this. Django does have a method to create static files with hashed names, but this route is just as effective with less code. Let me know if you would like to address this a different way.
The cache/file version is updated in the settings.py file. Then I am applying that version to only the .min versions of the files, not the un-minified versions that are used locally.
For testing steps, this can only be tested as-is in production. Locally, I added the version to the un-minified versions to confirm it was working as it should be.
=> TTWWW-595: Create Cache Buster for Prev Map Deployments

spectrum/autism_prevalence_map/static/autism_prevalence_map/ts/map.ts
This update is to address Sam's comment h[ere](https://simonsfoundation.atlassian.net/browse/TTWWW-473?focusedCommentId=114669).
I addressed his comment, so that zooming in will reform clusters based on the zoom level and new radius. I also added an enhancment to the auto zoom in and zoom out functionality we had based on a use case that this added. I created a video showing this, but basically when dots would form into smaller clusters after zooming in, then you expanded a mega dot, then clicked a dot close to but outside of that expanded mega dot, when it zoomed back out that clicked dot would form into a larger mega dot. I updated the experience so that when the user was auto zoomed into a mega dot when it expands, clicking out of it would auto zoom back out. But if a user manually …
=> TTWWW-473: Mega Dot zoom update based on QA

spectrum/autism_prevalence_map/static/autism_prevalence_map/ts/map.ts
These updates were to address Sam's comments [here](https://simonsfoundation.atlassian.net/browse/TTWWW-473?focusedCommentId=115168).
=> TTWWW-473: mega dot updates based on QA feedback
